AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PostZoomMeeting.lambda_handler
      Runtime: python3.8
      FunctionName: PostZoomMeeting1021
      CodeUri: .